#! /bin/bash


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1   -d     

bspc config border_width         	2
bspc config window_gap          	12
foreground              #c6d0f5
background              #303446
bspc config normal_border_color		"#303446"
bspc config active_border_color		"#303446"
bspc config focused_border_color	"#c6d0f5"
bspc config presel_feedback_color	"#c6d0f5"

bspc rule -a pavucontrol state=floating
bspc rule -a Pavucontrol state=floating

/home/bh/dev/dot/scripts/startup.sh
