#! /bin/sh

source ~/.config/bh/colors

sxhkd &
~/Development/scripts/startup.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	8
bspc config window_gap          	20
bspc config top_padding			60
bspc config normal_border_color		$PRIMARY_BACKGROUND
bspc config active_border_color		$PRIMARY_BACKGROUND
bspc config focused_border_color	$BRIGHT_BLUE
bspc config presel_feedback_color	$BRIGHT_BLUE

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

