#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0   -d     
bspc monitor HDMI-0 -d     

bspc config border_width         	2
bspc config window_gap          	32
# bspc config top_padding			60
bspc config normal_border_color		"#1E1E2E"
bspc config active_border_color		"#1E1E2E"
bspc config focused_border_color	"#CDD6F4"
bspc config presel_feedback_color	"#CDD6F4"

bspc rule -a pavucontrol state=floating
bspc rule -a Pavucontrol state=floating

/home/bh/dev/dot/scripts/startup_post.sh
