# background         = rgba(191724ff)   # base
background         = rgba(ffffffff)   # base
base               = rgba(1f1d2eff)   # surface
alternate_base     = rgba(26233aff)   # overlay
text               = rgba(908caaff)   # subtle
bright_text        = rgba(e0def4ff)   # text
accent             = rgba(31748fff)   # pine
accent_secondary   = rgba(c4a7e7ff)   # iris

font_family            = CommitMono Nerd Font Propo
font_family_monospace  = CommitMono Nerd Font Propo

rounding_large     = 4
rounding_small     = 4
