splash = false

$rightMonitor = desc:ASUSTek COMPUTER INC ASUS VG289 R9LMTF129424
$leftMonitor = desc:ASUSTek COMPUTER INC ASUS VG289 R9LMTF129416

wallpaper {
    monitor = $leftMonitor
    path = ~/Photos/linux.jpg
    fit_mode = cover
}

wallpaper {
    monitor = $rightMonitor
    path = ~/Photos/linux.jpg
    fit_mode = cover
}

