#! /bin/sh

source /home/arthur/.config/bh/colors

sxhkd &
~/Development/scripts/startup.sh

bspc monitor HDMI-0 	-d I II III IV V VI VII VIII IX X
# bspc monitor HDMI-0 	-d I II III IV V
# bspc monitor DVI-D-0	-d VI VII VIII IX X

bspc config border_width         	8
bspc config window_gap          	16
bspc config top_padding			50
bspc config normal_border_color		$GREY
bspc config active_border_color		$GREY
bspc config focused_border_color	$LIGHT_BLUE

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

