#!/bin/sh

if [ -z $1 ]; then
	echo $(tmux list-sessions)
	exit 0
fi
session="$1"

# set up tmux
tmux start-server

# session exists if error code for has session is 0
tmux has-session -t $session 2>/dev/null
if [ $? == 0 ]; then
  	tmux attach-session -t $session
	exit 0
fi

# create a new tmux session with window named "server"
tmux new-session -d -s $session -n server # create a second window name "vim"
tmux new-window -t $session -n vim

# select "server" window and attach
tmux select-window -t $session:0
tmux attach-session -t $session 
